"""empty message

Revision ID: 5f99d0dcc8fc
Revises: a3c3278053ca
Create Date: 2023-08-08 10:53:35.058179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f99d0dcc8fc'
down_revision = 'a3c3278053ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('first_player', sa.String(), nullable=True))
    op.drop_column('game', 'current_player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('current_player', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('game', 'first_player')
    # ### end Alembic commands ###
