"""empty message

Revision ID: 69a0dd6a4a35
Revises: ba80c9ad9d39
Create Date: 2023-08-04 20:31:50.307649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a0dd6a4a35'
down_revision = 'ba80c9ad9d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('user_move', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'user_move')
    # ### end Alembic commands ###
