"""empty message

Revision ID: b2f8e564a998
Revises: e47deb724278
Create Date: 2023-08-04 21:36:55.334140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2f8e564a998'
down_revision = 'e47deb724278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'board_init')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('board_init', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
