"""empty message

Revision ID: b3cd8d85a4c8
Revises: 5f99d0dcc8fc
Create Date: 2023-08-08 11:05:15.496282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cd8d85a4c8'
down_revision = '5f99d0dcc8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('white', sa.String(), nullable=True))
    op.drop_column('game', 'first_player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('first_player', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('game', 'white')
    # ### end Alembic commands ###
