"""empty message

Revision ID: ba80c9ad9d39
Revises: 766d430e7d89
Create Date: 2023-07-31 14:54:56.909466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba80c9ad9d39'
down_revision = '766d430e7d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_status', sa.String(), nullable=True))
    op.drop_column('game', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('game', 'game_status')
    # ### end Alembic commands ###
